services:
  client:
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/firebase-admin.json
    volumes:
      - type: bind
        source: ${FIREBASE_ADMIN_CREDENTIALS_FILE}
        target: /run/secrets/firebase-admin.json
        read_only: true

  server:
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/firebase-admin.json
    volumes:
      - type: bind
        source: ${FIREBASE_ADMIN_CREDENTIALS_FILE}
        target: /run/secrets/firebase-admin.json
        read_only: true
